apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reservations-hpa
  namespace: space-place
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reservations-deployment # deployment의 metadata.name과 매칭된다.
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
