apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-deployment
  namespace: space-place
  labels:
    app.kubernetes.io/name: members-deployment 
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: space-place
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: members-pod
  template:
    metadata:
      namespace: space-place
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: members-pod 
    spec:
      serviceAccountName: aws-credentials-serviceaccount
      nodeSelector:
        eks.amazonaws.com/nodegroup: test
      containers:
      - name: members-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/member:547565bfb2a1489a726ad074cc05f21c948c9008
          # image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/member:547565bfb2a1489a726ad074cc05f21c948c9008
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
      volumes:
        - name: secret-volume
          secret:
            secretName: aws-credentials
