apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: members-hpa
  namespace: space-place
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: members-deployment # deployment의 metadata.name과 매칭된다.
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
