apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: spaces-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/space:b6d254ae4c00002543ff919a67f767068a773075
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 50m
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
