apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: spaces-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/space:681053af867a7da99931dd9f30041a5a901fdcd2
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
