apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: reservations-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/reservation:fc7004c8af702679c865e27d2b9f897e6a0e9085
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
