apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: reservations-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/reservation:033ef11b5a9b68701a3fd91279fc9f32f6fa7cb4
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
