apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: reservations-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/reservation:b6d254ae4c00002543ff919a67f767068a773075
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 50m
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
