apiVersion: v1
kind: Service
metadata:
  name: dev-reservations-service
  namespace: space-place
spec:
  type: NodePort 
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app.kubernetes.io/name: dev-reservations-pod
