apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  namespace: space-place
  labels:
    app.kubernetes.io/name: payments-deployment 
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: space-place
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-pod
  template:
    metadata:
      namespace: space-place
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: payments-pod 
    spec:
      serviceAccountName: aws-credentials-serviceaccount
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - sp-general
                - sp-spot
      containers:
      - name: payments-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/payment:a003f680f6ffea192b2044467744bfefca5f3062
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
      volumes:
        - name: secret-volume
          secret:
            secretName: aws-credentials
        - name: ca
          secret:
            secretName: ca
