apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payments-hpa
  namespace: space-place
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payments-deployment # deployment의 metadata.name과 매칭된다.
  minReplicas: 5
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
