apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces-deployment
  namespace: space-place
  labels:
    app.kubernetes.io/name: spaces-deployment 
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: space-place
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spaces-pod
  template:
    metadata:
      namespace: space-place
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: spaces-pod 
    spec:
      serviceAccountName: aws-credentials-serviceaccount
      containers:
      - name: spaces-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/space:4a23f2f11ab51b00b2eb9243c3e7fc76b7152ef3
          # image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/space:4a23f2f11ab51b00b2eb9243c3e7fc76b7152ef3
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
          - name: ca
            mountPath: /etc/ssl/certs
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        resources:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 512Mi
            cpu: 50m
      volumes:
        - name: secret-volume
          secret:
            secretName: aws-credentials
        - name: ca
          secret:
            secretName: ca
