apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces-deployment
  namespace: space-place
  labels:
    app.kubernetes.io/name: spaces-deployment 
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: space-place
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spaces-pod
  template:
    metadata:
      namespace: space-place
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: spaces-pod 
    spec:
      serviceAccountName: aws-credentials-serviceaccount
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - sp-general
                - sp-spot

      containers:
      - name: spaces-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/space:2dbc981ed2c778859dd505f53225a85db099ad98
          # image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/space:2dbc981ed2c778859dd505f53225a85db099ad98
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
          - name: ca
            mountPath: /etc/ssl/certs
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 10
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
      volumes:
        - name: secret-volume
          secret:
            secretName: aws-credentials
        - name: ca
          secret:
            secretName: ca
