apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spaces-hpa
  namespace: space-place
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spaces-deployment # deployment의 metadata.name과 매칭된다.
  minReplicas: 8
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
