apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: payments-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/payment:a8cef2514601202114b61974e5723373bc803fed
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 45
          periodSeconds: 5
