apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: members-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/member:78743bd08168fd7cad0cf6e9dad5911d30524a1f
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
