apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-deployment
  namespace: space-place
spec:
  template:
    metadata:
      namespace: space-place
    spec:
      containers:
      - name: members-container
        image: 148761649775.dkr.ecr.ap-northeast-2.amazonaws.com/space-place/member:5b4d3aa15cdfa6552ed24158cb7450443a4af83f
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 50m
